config/routes.rb
Rails.application.routes.draw do
  #get 'categories/pages'
  devise_for :users
  root to: 'pages#home'
  get "/about", to: "pages#about"
  resources :categories do
    resources :posts, except: [ :index, :show ]
  end
  resources :posts, only: [ :edit, :update, :destroy ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts, dependent: :destroy

  has_one_attached :photo
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :category

  validates :title, :description, :photos, presence: true #photos?

  has_many_attached :photos
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # method that comes with devise that check if the user is logged in
    before_action :authenticate_user!
end

# app/controllers/application_controller.rb

def default_url_options
  { host: ENV["DOMAIN"] || "localhost:3000" }
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :check_admin?, except: [:index, :show]
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @categories = Category.all
  end

  def show
    # sql
    # select * from posts where post.category_id = @category.id
    # posts = Post.where("post.category_id = ?", @category.id)
    # active record
    # todos os posts desta categoria
    @posts = Post.where(category: @category)
    @photos = []
    @posts.each do |post|
      post.photos.each do |photo|
        photo_post = Post.find(photo.record_id)
        @photos << {
          photo: photo,
          description: photo_post.description,
          title: photo_post.title
        }
      end
    end
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    @category.save

    redirect_to category_path(@category)
  end

  def edit
  end

  def update
    if @category.update(category_params)
      redirect_to category_path(@category), notice: 'Category updated successfully'
    else
      render :edit
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy!

    redirect_to categories_path
  end

    private

  def category_params
    params.require(:category).permit(:title, :photo)
  end

  def set_category
    @category = Category.find(params[:id])
  end

  def check_admin?
    # check if the logged user is an admin or not!
    if current_user && current_user.admin != true
      redirect_to root_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :about]
  def home
  end

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :set_post, only: [:edit, :update, :destroy]

  def new
    @category = Category.find(params[:category_id])
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @category = Category.find(params[:category_id])
    @post.category = @category
    if @post.save
      redirect_to category_path(@category)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)

      redirect_to category_path
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy!
    redirect_to category_path(@post.category)
  end

  private

  def post_params
    params.require(:post).permit(:title, :description, :photos => [])
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/categories/edit.html.erb
<!-- app/views/reviews/new.html.erb -->
<div class="container">
  <div class="add-post"> 
    <%= simple_form_for @category do |f| %>
      <%= f.input :title, input_html: { autocomplete: 'off' } %>
      <%= f.input :photo, as: :file %>
      <%= f.submit "NEXT", class: "btn btn-primary" %>
    <% end %>
    <%= link_to 'Back to categories', categories_path(@category) %>
  </div>
</div>

app/views/categories/index.html.erb
<% if current_user && current_user.admin %>
  <%= link_to '+ Add category', new_category_path, class: "btn btn-outline-dark mt-4 ml-3 mb-4" %>
<% end %>
<div class="container">
  <div class="row">
    <% @categories.each do |category| %>
      <%= link_to category_path(category), class: "categories-card" do %>
        <div class="col-md-6 col-xs-12 mb-3">
          <div class="exp-card-head mt-4">
            <div class="card-style-category">
              <h4><%= category.title %></h4>
              <% if category.photo.attached? %>
                  <%= cl_image_tag category.photo.key, height: 400, width: 500, crop: :fill, class: "card-photo" %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/categories/new.html.erb
<!-- app/views/reviews/new.html.erb -->
<div class="container">
  <div class="add-post"> 
    <%= simple_form_for @category do |f| %>
      <%= f.input :title, input_html: { autocomplete: 'off' } %>
      <%= f.input :photo, as: :file %>
      <%= f.submit "NEXT", class: "btn btn-primary" %>
    <% end %>
    <%= link_to 'Back to categories', categories_path(@category) %>
  </div>
</div>

app/views/categories/show.html.erb
<%= link_to '⬅ Back', categories_path(@categories), class: "btn btn-outline-dark ml-3 mt-2" %>
<br>
<% if current_user && current_user.admin %>
<%= link_to 'Add 📷', new_category_post_path(@category), class: "btn btn-outline-dark mt-2 ml-3" %>
<% end %>
<div class="container h-100 ">
  <div class="row h-100 ">
    <div class="col-md-12 text-center">
          <div class="category-header">
            <h1><%= @category.title  %></h1>
          </div>
        <div class="test-center">
          <% if @photos.present? %>
            <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel"  data-interval="false" data-interval="500">
              <%# <ol class="carousel-indicators">
                <li data-target="#" data-slide-to="0" class="active"></li>
                <li data-target="#" data-slide-to="1"></li>
                <li data-target="#" data-slide-to="2"></li>
                <li data-target="#" data-slide-to="3"></li>
                <li data-target="#" data-slide-to="4"></li>
                <li data-target="#" data-slide-to="5"></li>
                <li data-target="#" data-slide-to="6"></li>
                <li data-target="#" data-slide-to="7"></li>
                <li data-target="#" data-slide-to="8"></li>
                <li data-target="#" data-slide-to="9"></li> %>

                <%# <li data-target="#carouselExampleIndicators" data-slide-to="2"></li> %>
              </ol>
              <div class="carousel-inner">
                <div class="carousel-item active">
                  <%= cl_image_tag @photos.first[:photo].key, class:"image-slider", crop: :fill %>
                 <!-- <div class="carousel-caption d-none d-md-block">
                    <h5><%= @photos.first[:title] %></h5>
                    <p><%= @photos.first[:description] %></p>
                  </div>-->
                </div>
                <% @photos[1..-1].each do |photo| %>
                    <div class="carousel-item">
                      <%= cl_image_tag photo[:photo].key, class:"image-slider", crop: :fill %>
                      <!--<div class="carousel-caption d-none d-md-block">
                        <h5><%= photo[:title] %></h5>
                        <p><%= photo[:description] %></p>
                      </div>-->
                    </div>
                <% end %>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                  <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
                  <span class="sr-only">Next</span>
                </a>
              </div>
            </div>
          <% end %>
        </div>
          <div class="crud-links-general d-flex justify-content-around mt-4 mb-4">
            <% if current_user && current_user.admin %>
              <%= link_to "Delete Category", category_path(@category.id), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-outline-danger" %>
              <%= link_to 'Edit Category', edit_category_path(@category), class: "btn btn-outline-secondary" %>
            <%end %>
          </div>
     </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= meta_title %></title>
    
    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">
    <%= favicon_link_tag asset_path('foto5.jpg') %>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <div class="page-container-global">
      <% unless current_page?(root_path) %>
        <div class="navbar-container sticky-top">
          <%= render 'shared/navbar' %>
        </div>
      <% end %>
      <%# <div class="navbar-flash"><%= render 'shared/flashes' %>
        <div class="content-container">
          <%= yield %>
        </div>
      <div class="footer-container">
        <%= render 'shared/footer' %>
      </div>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container">
<%# <%= link_to 'Photos', categories_path(@categories) %> 
<%# <%= link_to '<- Back', root_path %>  
  <div class="about-content"> 
  
   </div>    
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner">
  <div class="banner-content" >
    <div class="logos">
        <div class="logo">
          <h6>Gabriel Campista</h6>
        </div>
        <div class="logo">
          <h5>Photography</h5>
        </div>
      </div>
      <div class="banner-buttons">
        <%= link_to "come in", categories_path, class: "btn button-home" %>
        <%= link_to "about me", about_path, class: "btn button-home" %>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<h2>edit post</h2>

<%# someday remember to make a simple form for edit picture %>

app/views/posts/new.html.erb
<div class="container"> 
  <br>
  <div class="add-post"> 
    <h5><strong>Add photo</strong></h5>
    <%= simple_form_for [ @category, @post ] do |f| %>
      <%= f.input :title,  { autocomplete: 'off' } %>
      <%= f.input :description, { autocomplete: 'off' } %>
      <br>
      <%= f.input :photos, as: :file, input_html: { multiple: true } %>
      <br>
      <%= f.submit "Add photo", class: "btn btn-primary" %>
    <% end %>
    <%= link_to 'Back to categories', categories_path(@category) %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="content-footer d-flex flex-column">
  <div class="footer-row">
    <div class="col-md-12 center">
      <ul class="social-icons mb-md list-unstyled d-flex justify-content-around" >
         <li class="mt-3 ml-2"> gcampss@gmail.com</li>

        <li class="mt-3 ml-2"><a href="https://www.instagram.com/campista/" target="_blank" title="Instagram"> <%= icon('fab', 'instagram') %></a>  
        </li>
        <li class="mt-3 ml-2"><a href="https://www.linkedin.com/in/gabrielcampista/" target="_blank" title="Linkedin"> <%= icon('fab', 'linkedin') %></a>   
        </li>
        <li class="mt-3 ml-2"><a href="https://github.com/gcampss" target="_blank" title="GitHub"> <%= icon('fab', 'github') %></a>  
      </ul>        
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <div class="logo-font-banner1">
      <%= "Gabriel Campista" %>
     </div>
    <div class="logo-font-banner2">
      <%= "Photography" %>
    </div>
  <% end %>

  <i class="fas fa-bars dropdown-burger" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></i>
  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
    <%= link_to "photos",categories_path, class: "dropdown-item" %>
    <%= link_to "about me", about_path, class: "dropdown-item" %>
    <%= link_to "contact", "contant_path", class: "dropdown-item" %>
    <%= link_to "instagram","https:/instagram.com/campista", target: "_blank", class: "dropdown-item" %>
    <% if user_signed_in? %>
      <%= link_to "log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
    <% end %>
  </div>
</div>